# Generated by Django 4.2.26 on 2025-11-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wellness_score', models.FloatField()),
                ('productivity_score', models.FloatField()),
                ('stress_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('avg_mood', models.FloatField()),
                ('avg_sleep', models.FloatField()),
                ('avg_stress', models.FloatField()),
                ('avg_energy', models.FloatField()),
                ('total_study_time', models.IntegerField()),
                ('productivity_score', models.FloatField()),
                ('wellness_score', models.FloatField()),
                ('best_day', models.CharField(max_length=20)),
                ('worst_day', models.CharField(max_length=20)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
